### ISSUE TITLE
ElottieSharp Xamarin Forms DLL library not found liblottie-player.so.0 in wereable simulator

### ISSUE THREAD

**Issue by tec-tea** [TizenAPI/ElottieSharp#13]
**Describe the bug**
Library liblottie-player.so.0 not found error when launch in wereable simulator, works fine in real device.

**To Reproduce**

**XAML file**
`<w:CirclePage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:w="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
             NavigationPage.HasNavigationBar="False"
             mc:Ignorable="d"
             x:Class="SomeProject.Views.SomeView">
<w:CirclePage.Content>
<StackLayout x:Name="layout">
</StackLayout>
</w:CirclePage.Content>
</w:CirclePage>`

**Code Behind (for debugging purposes)**

`namespace SomeProject.Views
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class SomeView: CirclePage
    {
        public SomeView()
        {
            InitializeComponent();
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();

            try
            {
                var animation = new ElottieAnimationView
                {
                    AnimationFile = "somelottiefile.json",
                    AutoPlay = true,
                    AutoRepeat = true,
                    HorizontalOptions = LayoutOptions.FillAndExpand,
                    VerticalOptions = LayoutOptions.FillAndExpand
                };

                // Play the animation

                layout.Children.Add(animation);
                animation.Play();
            }
            catch (Exception e)
            {
                Console.WriteLine("Error: " + e.Message);
            }
          
        }
    }
}`

**Expected behavior**
Page should load correctly and lottie animation shown in screen (works fine in real device)

**Screenshots**
![image](https://user-images.githubusercontent.com/41548471/75183522-a10e2580-573a-11ea-964d-4745ddbd2a50.png)

**Environment:**
 - Tizen.NET.Sdk/1.0.9
 - Visual Studio 16.4.3
 - ElottieSharp.Forms 0.9.5-preview
 - Tizen 4.0
 - Tizen Emulator: wereable-4.0-circle-x86-preview 26101, SDK 3.6, package version 2.8.0.24

**Additional context**
Love Tizen .NET platform, keep the good work!

**Comment by rookiejava** [comment]
Thank you for describing. It helps find out what's wrong. :-)

**Comment by rookiejava** [comment]
We found that in the latest version of VS, runtime target asests that RID is not specified  (e.g. runtimes/native/*.so) are not included when packaging. 

So, as you reported, it seems to haven't found `liblottie-player.so.0` when run on the emulator. (In case of target devices, it already contains the corresponding `*.so` in the platform binary, so you don't have to find the liblottie-player.so.0` in the nupkg. This is why only real device works well.)

Anyway, firstly, to make sure that your problem is solved, could you test again after modifying your project file (`*.csproj`) as below.  (Add below single line into `<PropertyGroup>` in your project.)

```xml
<CopyLocalRuntimeTargetAssets>true</CopyLocalRuntimeTargetAssets>
```

**Comment by EmilAlipiev** [comment]
using `<CopyLocalRuntimeTargetAssets>true</CopyLocalRuntimeTargetAssets>`
Works for me on both emulator and device. 
But there is something missing in documentation and it wasted some time for me. 
If you use ElottieAnimationView as single child, it works as default above code. But if you use it in stacklayout with other children like 
 ```
 <Stacklayout>
        <Label />
        <Label />
           <e:ElottieAnimationView  
                 AnimationFile = "loading.json" AutoPlay = "True" AutoRepeat="True"
                  HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"/>
</Stacklayout>
```
It wont appear. Only way to make this working is to give fix  WidthRequest="72" HeightRequest="72" like this. I think that it is only able to fill the main container when it is single child. I tried also within an Absolutelayout as below. It doesnt appear. Only giving WidthRequest and WidthRequest works

```
  <AbsoluteLayout  VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
            <e:ElottieAnimationView x:Name="animation"  AbsoluteLayout.LayoutFlags="PositionProportional"
               AbsoluteLayout.LayoutBounds=".5, .5, -1, -1" AnimationFile = "loading.json" AutoPlay = "True" AutoRepeat="True"
                  HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"/>
 
        </AbsoluteLayout>
```

**Comment by rookiejava** [comment]
@EmilAlipiev, yes you're right. The initial size of `ElottieAnimationView`  is zero as  I described in both [project readme](https://github.com/TizenAPI/ElottieSharp) file and dev guide in [release note](https://github.com/TizenAPI/ElottieSharp/releases). So. you should set `WidthRequest` and `HeightRequest` property to request the size of view. 

![ellot](https://user-images.githubusercontent.com/1029134/75644991-abbf4200-5c87-11ea-8ff2-406031d02cce.png)

Anyway, I'm sorry to have made you waste a lot of your time.  

Thanks.

**Comment by rookiejava** [comment]
@ismasanchez  Please re-open this issue if you still have problem.
