### ISSUE TITLE
Fix the source code

### ISSUE THREAD

**Issue by EmilAlipiev** [TizenAPI/ElottieSharp#14]
When you clone or download the project and open in VS2019, it is not runable. It has a lot of errors. I want to contribute it but i dont understand why project is not just working with a lot of references broken and restore of the packages are not possible.

**Comment by rookiejava** [comment]
Thank you for reporting. I'll check quickly.

**Comment by rookiejava** [comment]
Hi @EmilAlipiev, I've clone and download the project and open in VS2019 (16.3.9) as you reported. 
But, I didn't find any special error message as shown below.

![elottie](https://user-images.githubusercontent.com/1029134/75638984-ef0eb600-5c71-11ea-8937-2bb76c4a39a8.png)

Could you tell me more about what error occurred?

**Comment by EmilAlipiev** [comment]
strange. i really struggled with a lot of errors. I will try later with clean download.

**Comment by EmilAlipiev** [comment]
I am using VS2019 16.4.5. I believe problem is as explained in the article below. When you adjust based on the suggestions in the article, it should be working fine. 

https://samsung.github.io/Tizen.NET/tizen%20.net/Using-Tizen-NET-Sdk-as-SDK-style/

**Comment by rookiejava** [comment]
Ah, did you mean an error that occurred in the sample app project? Anyway I've updated the sample app projects. Thanks.
