### ISSUE TITLE
Couldn't work on Galaxy Watch Active 2

### ISSUE THREAD

**Issue by rookiejava** [TizenAPI/ElottieSharp#9]
It doesn't work with Galaxy Watch Active 2 (Tizen Version : 4.0.0.6).

**Comment by JoonghyunCho** [comment]
oh no.. 😢

**Comment by rookiejava** [comment]
@JoonghyunCho don't cry. Now it works. :stuck_out_tongue_winking_eye:

**Comment by EmilAlipiev** [comment]
what did you do to make it work? it doesnt work for me on Active 1 ?
